import json
import re

file_path = "/Users/pratham/Desktop/Sandbox/Dating App/backend/intake_questions.py"

with open(file_path, "r") as f:
    content = f.read()

# Define the new probe bundles
replacements = {
    '"id": "15.4", "text": "If your parent and your spouse are in conflict, your first duty is to:", "format": "multiple_choice", "options": ["Protect fairness", "Protect spouse", "Protect parent", "De-escalate first", "Stay neutral"]': 
    '"id": "15.4", "text": "If your parent and your spouse are in conflict, your first duty is to:", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "multiple_choice", "options": ["Protect fairness", "Protect spouse", "Protect parent", "De-escalate first", "Stay neutral"]}, {"id": "emotion", "text": "What emotion drives this choice?", "type": "multiple_choice", "options": ["Fear of family judgment", "Anger at injustice", "Desire for peace", "Loyalty to spouse"]}, {"id": "reflection", "text": "What is the hardest part of this choice?", "type": "short_answer"}]',
    
    '"id": "13.5", "text": "If grandparents break the parents’ rules, the couple should:", "format": "sjt", "options": [{"id": "ignore", "text": "Ignore it"}, {"id": "correct", "text": "Correct privately later"}, {"id": "firm", "text": "Set firm boundary immediately"}, {"id": "adjust", "text": "Adjust rules to avoid conflict"}]':
    '"id": "13.5", "text": "If grandparents break the parents’ rules, the couple should:", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "sjt", "options": [{"id": "ignore", "text": "Ignore it"}, {"id": "correct", "text": "Correct privately later"}, {"id": "firm", "text": "Set firm boundary immediately"}, {"id": "adjust", "text": "Adjust rules to avoid conflict"}]}, {"id": "emotion", "text": "What are you feeling most?", "type": "multiple_choice", "options": ["Disrespect", "Guilt", "Frustration", "Indifference"]}, {"id": "reflection", "text": "How much does your partner\'s reaction matter here?", "type": "short_answer"}]',
    
    '"id": "16.2", "text": "If a senior family member makes intrusive comments about intimacy, what should happen?", "format": "sjt", "options": [{"id": "stop", "text": "Firmly stop conversation"}, {"id": "laugh", "text": "Laugh it off/Move on"}, {"id": "later", "text": "Change topic/set boundary later"}, {"id": "tolerate", "text": "Tolerate for respect"}]':
    '"id": "16.2", "text": "If a senior family member makes intrusive comments about intimacy, what should happen?", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "sjt", "options": [{"id": "stop", "text": "Firmly stop conversation"}, {"id": "laugh", "text": "Laugh it off/Move on"}, {"id": "later", "text": "Change topic/set boundary later"}, {"id": "tolerate", "text": "Tolerate for respect"}]}, {"id": "emotion", "text": "What emotion do you feel?", "type": "multiple_choice", "options": ["Embarrassment", "Anger", "Amusement", "Shame"]}, {"id": "reflection", "text": "What is your internal thought at that moment?", "type": "short_answer"}]',
    
    '"id": "18.13", "text": "SJT: Your partner wants to decide immediately, but you need time to think. What are you most likely to do?", "format": "sjt", "options": [{"id": "commitment", "text": "Ask for time and commit to a specific revisit point"}, {"id": "force", "text": "Force yourself to decide now"}, {"id": "shutdown", "text": "Shut down the conversation"}, {"id": "agree_later", "text": "Agree now and revisit later"}, {"id": "consult", "text": "Ask a third person for input"}]':
    '"id": "18.13", "text": "SJT: Your partner wants to decide immediately, but you need time to think. What are you most likely to do?", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "sjt", "options": [{"id": "commitment", "text": "Ask for time and commit to a specific revisit point"}, {"id": "force", "text": "Force yourself to decide now"}, {"id": "shutdown", "text": "Shut down the conversation"}, {"id": "agree_later", "text": "Agree now and revisit later"}, {"id": "consult", "text": "Ask a third person for input"}]}, {"id": "emotion", "text": "What drives this response?", "type": "multiple_choice", "options": ["Anxiety to please", "Need for control", "Overwhelm", "Desire for fairness"]}, {"id": "reflection", "text": "What would make you feel safer deciding now?", "type": "short_answer"}]',
    
    '"id": "18.14", "text": "SJT: A family conflict needs a decision by tonight, but both spouses feel unheard. What happens next?", "format": "sjt", "options": [{"id": "practical", "text": "Prioritize the practical decision and repair later"}, {"id": "delay", "text": "Delay the decision if possible"}, {"id": "charge", "text": "One partner takes charge"}, {"id": "elders", "text": "Ask elders to decide"}, {"id": "compromise", "text": "Find the least damaging compromise"}]':
    '"id": "18.14", "text": "SJT: A family conflict needs a decision by tonight, but both spouses feel unheard. What happens next?", "format": "probe_group", "probes": [{"id": "action", "text": "What happens next?", "type": "sjt", "options": [{"id": "practical", "text": "Prioritize the practical decision and repair later"}, {"id": "delay", "text": "Delay the decision if possible"}, {"id": "charge", "text": "One partner takes charge"}, {"id": "elders", "text": "Ask elders to decide"}, {"id": "compromise", "text": "Find the least damaging compromise"}]}, {"id": "emotion", "text": "What is the primary emotion?", "type": "multiple_choice", "options": ["Resentment", "Urgency", "Sadness", "Detachment"]}, {"id": "reflection", "text": "How will this affect tomorrow?", "type": "short_answer"}]',
    
    '"id": "12.2", "text": "If a career opportunity arises elsewhere, we should:", "format": "multiple_choice", "options": ["Move for opportunity", "Prefer husband’s", "Prefer wife’s", "Case-by-case", "Stay near family"]':
    '"id": "12.2", "text": "If a career opportunity arises elsewhere, we should:", "format": "probe_group", "probes": [{"id": "action", "text": "What is the rule?", "type": "multiple_choice", "options": ["Move for opportunity", "Prefer husband’s", "Prefer wife’s", "Case-by-case", "Stay near family"]}, {"id": "emotion", "text": "If you had to sacrifice, you would feel:", "type": "multiple_choice", "options": ["Resentful", "Accepting", "Indifferent", "Proud"]}, {"id": "reflection", "text": "What makes the sacrifice worth it?", "type": "short_answer"}]',
    
    '"id": "14.3", "text": "If both parents need support, priority is:", "format": "multiple_choice", "options": ["Husband’s parents", "Wife’s parents", "Equal", "Need-based", "Sacrifice-based"]':
    '"id": "14.3", "text": "If both parents need support, priority is:", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "multiple_choice", "options": ["Husband’s parents", "Wife’s parents", "Equal", "Need-based", "Sacrifice-based"]}, {"id": "emotion", "text": "How do you feel about this expectation?", "type": "multiple_choice", "options": ["Trapped", "Dutiful", "Resentful", "Honored"]}, {"id": "reflection", "text": "What happens to the marriage when this occurs?", "type": "short_answer"}]',
    
    '"id": "17.3", "text": "If communication suddenly drops, I usually:", "format": "multiple_choice", "options": ["Get anxious", "Give space", "Assume wrong", "Distract myself", "Reach out directly", "Wait calmly"]':
    '"id": "17.3", "text": "If communication suddenly drops, I usually:", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "multiple_choice", "options": ["Get anxious", "Give space", "Assume wrong", "Distract myself", "Reach out directly", "Wait calmly"]}, {"id": "emotion", "text": "What is your underlying fear?", "type": "multiple_choice", "options": ["Abandonment", "Disrespect", "Rejection", "None"]}, {"id": "reflection", "text": "How long until you react?", "type": "short_answer"}]',
    
    '"id": "10.2", "text": "If a spouse has a different diet from the family, what should happen?", "format": "multiple_choice", "options": ["Family rules dominate", "Separate arrangements", "Spouse adjust for peace", "Mutual compromise", "Depends on ownership"]':
    '"id": "10.2", "text": "If a spouse has a different diet from the family, what should happen?", "format": "probe_group", "probes": [{"id": "action", "text": "What should happen?", "type": "multiple_choice", "options": ["Family rules dominate", "Separate arrangements", "Spouse adjust for peace", "Mutual compromise", "Depends on ownership"]}, {"id": "emotion", "text": "If forced to eat separately, you would feel:", "type": "multiple_choice", "options": ["Alienated", "Relieved", "Indifferent", "Angry"]}, {"id": "reflection", "text": "Is food about respect or just sustenance?", "type": "short_answer"}]',
    
    '"id": "4.5", "text": "If someone crosses a boundary with your spouse in front of you:", "format": "multiple_choice", "options": ["defend", "calm", "silent", "private"]':
    '"id": "4.5", "text": "If someone crosses a boundary with your spouse in front of you:", "format": "probe_group", "probes": [{"id": "action", "text": "What do you do?", "type": "multiple_choice", "options": ["defend", "calm", "silent", "private"]}, {"id": "emotion", "text": "What do you feel?", "type": "multiple_choice", "options": ["Protective anger", "Social anxiety", "Paralysis", "Annoyance"]}, {"id": "reflection", "text": "Why didn\'t you choose a different path?", "type": "short_answer"}]'
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open(file_path, "w") as f:
    f.write(content)

print("Scenarios updated to probe bundles.")
